import { ThemeProvider } from '@/context/theme-provider'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import MainLayout from '@/layout/main-layout'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <MainLayout>
            {children}
          </MainLayout>
        </ThemeProvider>
      </body>
    </html >
  )
}
